apiVersion: v2
type: application
description: A Helm chart to deploy the Capsule Operator for easily implementing,
  managing, and maintaining mutitenancy in Kubernetes.
home: https://github.com/clastix/capsule
icon: https://github.com/clastix/capsule/blob/master/assets/logo/space-capsule3.png
keywords:
- kubernetes
- operator
- multi-tenancy
- multi-tenant
- multitenancy
- multitenant
- namespace
maintainers:
- email: hello@clastix.io
  name: Clastix Labs Team
name: capsule
sources:
- https://docs.couchbase.com/operator/current/helm-setup-guide.html

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.0.1

# This is the version number of the application being deployed.
# This version number should be incremented each time you make changes to the application.
appVersion: 0.0.0