# Default values for capsule.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  # Specifies whether a custom namespace should be created is not yet supported.
  # If false default to "capsule-system"
  create: false
  # The name namespace to use.
  # If not set and create is true, default to "capsule-system"
  name: ""

force_tenant_prefix: true
log_level: 10

manager:
  image:
    repository: quay.io/clastix/capsule
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 128Mi
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

proxy:
  image:
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v0.5.0"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "capsule"

podAnnotations: {}

podSecurityPolicy:
  enabled: true

podSecurityContext: {}

priorityClassName: system-cluster-critical
nodeSelector:
  node-role.kubernetes.io/master: ""
tolerations:
- key: CriticalAddonsOnly
  operator: Exists
- effect: NoSchedule
  key: node-role.kubernetes.io/master

replicaCount: 1
affinity: {}