apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "capsule.labels" . | nindent 4 }}
  name: {{ include "capsule.fullname" . }}-tls
  namespace: {{ include "capsule.namespace" . }}
data:
