apiVersion: v1
kind: Service
metadata:
  name: {{ include "capsule.fullname" . }}-webhook-service
  namespace: {{ include "capsule.namespace" . }}
  labels:
    {{- include "capsule.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    name: https
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "capsule.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
